services:
  - type: web
    name: jobfit
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py runserver"
    mounts:
      - source: jobfit-db
        destination: /app/db.sqlite3
    plan: free
    region: oregon
