# Generated by Django 5.1.3 on 2024-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='required_skills',
            new_name='skills_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='job_experience',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='job_role',
            field=models.CharField(default='Unknown Role', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
