# Generated by Django 5.1.3 on 2024-12-02 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_rename_required_skills_job_skills_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='matched', max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.job')),
            ],
        ),
    ]
