# Generated by Django 5.1.3 on 2024-12-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_applicant_status_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='status',
        ),
        migrations.DeleteModel(
            name='JobMatch',
        ),
    ]
