# Generated by Django 5.1.3 on 2024-12-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_feedback_rating_feedback_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecommendation',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
