# Generated by Django 5.1.3 on 2024-12-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_jobrecommendation_similarity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecommendation',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobrecommendation',
            name='similarity_score',
            field=models.FloatField(),
        ),
    ]
