# Generated by Django 5.1.3 on 2024-12-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_jobrecommendation_is_relevant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='applicant', max_length=20),
        ),
    ]
